services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
      target: base_stacks
    image: "mokztk/r_base:4.5.3"

  rstudio:
    build:
      context: .
      dockerfile: Dockerfile
      target: rstudio
    image: "mokztk/rstudio:4.5.3"
    depends_on:
      - base
    ports:
      - "8787:8787"
    environment:
      - DISABLE_AUTH=true

  ssh:
    build:
      context: .
      dockerfile: Dockerfile
      target: ssh
    image: "mokztk/r_remote:4.5.3"
    depends_on:
      - base
    ports:
      - "22222:22"

  codeserver:
     build:
       context: .
       dockerfile: Dockerfile
       target: codeserver
     image: "mokztk:codeserver_r:4.5.3"
    depends_on:
      - base
    ports:
      - "8080:8080"
      - "8088:8088"
