services:
  code_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: "mokztk/codeserver_r:4.5.3"
    container_name: "codeserver"
    ports:
      - "8080:8080"
      - "8088:8088"
    volumes:
      - ./settings.json:/home/coder/.local/share/code-server/User/settings.json
