---
title: "Test Document"
date: "`r Sys.Date()`"
date-format: iso
format:
  html: 
    fontsize: normal
    page-layout: full
    fig-format: svg
    fig-dev: svglite
    fig-width: 9
    fig-height: 5.625   # 8:5
    self-contained: true
    code-fold: show
    code-block-border-left: true
    code-line-numbers: false
    code-overflow: wrap
    highlight-style: atom-one
    df-print: tibble
---

```{r}
#| message: false

pacman::p_load(tidyverse)
pacman::p_install("hexbin", force = FALSE)

diamonds |> 
  ggplot(aes(x = carat, y = price, fill = clarity)) +
  geom_hex(linewidth = .5, colour = "white") +
  ggsci::scale_fill_observable() +
  labs(
    x = "carat は重さ≒大きさ",
    y = "price in USD"
  ) +
  theme_minimal(base_family = "Noto Sans JP", base_size = 18)
```

# Tools

## Pandoc and Quarto

```{r}
system("which pandoc; pandoc --version", intern = TRUE) |> 
  paste(collapse = "\n") |> 
  cat()
```

```{r}
system("which quarto; quarto --version", intern = TRUE) |> 
  paste(collapse = "\n") |> 
  cat()
```

```{r}
system("quarto pandoc --version", intern = TRUE) |> 
  paste(collapse = "\n") |> 
  cat()
```

```{r}
system("quarto typst --version 2>&1", intern = TRUE) |> 
  paste(collapse = "\n") |> 
  cat()
```

## Node.js and npm, pnpm

```{r}
system("pnpm --version", intern = TRUE) |> 
  paste(collapse = "\n") |> 
  cat()

system("pnpm config list", intern = TRUE) |> 
  paste(collapse = "\n") |> 
  cat()
```

```{r}
system("npm --version", intern = TRUE) |> 
  paste(collapse = "\n") |> 
  cat()
```

```{r}
system("node --version", intern = TRUE) |> 
  paste(collapse = "\n") |> 
  cat()
```

## Others

```{r}
system("msedit --version", intern = TRUE) |> 
  paste(collapse = "\n") |> 
  cat()
```

```{r}
system("which python; python --version", intern = TRUE) |> 
  paste(collapse = "\n") |> 
  cat()
```

```{r}
system("which uv; uv --version", intern = TRUE) |> 
  paste(collapse = "\n") |> 
  cat()
```

```{r}
reticulate::py_config()
```

# Session info


```{r}
sessioninfo::session_info(pkgs = .packages(all.available = TRUE))
```
